from enum import Enum


class VerificationStatus(str, Enum):
    VERIFIED = "VERIFIED"
    ADDITIONAL_CAPTURE_REQUIRED = "ADDITIONAL_CAPTURE_REQUIRED"
    REJECTED = "REJECTED"


class ReasonCode(str, Enum):
    INVALID_FILE = "INVALID_FILE"
    IMAGE_TOO_BLURRY = "IMAGE_TOO_BLURRY"
    IMAGE_TOO_DARK = "IMAGE_TOO_DARK"
    OCR_STRONG_MATCH = "OCR_STRONG_MATCH"
    OCR_MEDIUM_MATCH = "OCR_MEDIUM_MATCH"
    VISION_STRONG_MATCH = "VISION_STRONG_MATCH"
    VISION_MEDIUM_MATCH = "VISION_MEDIUM_MATCH"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    OUT_OF_RADIUS = "OUT_OF_RADIUS"
